services:
  api:
    env_file:
      - .env
    container_name: api
    platform: linux/x86_64
    hostname: localhost
    tty: true
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./backend:/go/src/app
    command: sh -c "go mod tidy && air -c .air/.api.toml"
